#!/bin/bash
#PBS -q batch
#PBS -V
#PBS -l walltime=96:00:00
#PBS -l nodes=8:ppn=32
#PBS -N vo
#PBS -j oe


JOBSEED=V2O3-I12a1
JOBDOS=${JOBSEED}_PhonDOS
JOBDISP=${JOBSEED}_PhonDisp

cd $PBS_O_WORKDIR

date
mpirun -np 256 $CASTEP_MPI_FLAGS castep.mpi $JOBSEED
cp ${JOBSEED}.check ${JOBDOS}.check
mpirun -np 256 $CASTEP_MPI_FLAGS castep.mpi $JOBDOS
cp ${JOBDOS}.check ${JOBDISP}.check
mpirun -np 256 $CASTEP_MPI_FLAGS castep.mpi $JOBDISP

