class ElementData:
    """
    Class for storing some data about the chemical elements.

    elementnr          :  dictionary of the element numbers.
                         Example: elementnr['O'] is 8.
    valenceelectrons   :  Number of valence electrons.
    elementperiod      :  Which period?
    elementblock       :  dictionary of which block an element belong to (spdf).
                         Example: elementblock['Fe'] is 'd'
    elementweight      :  dictionary of atomic weights (IUPAC 2009)
    angularmomentum    :  dictionary for the angular momentum quantum number of s,p,d,f states
    vasp_pot
    vasp_cutoff
    castep_recpot
    castep_usp
    """
    def __init__(self):
        # Element numbers
        self.elementnr = {
            'Em' : 0  , # empty site 
            'Vc' : 0  , # empty site
            'Va' : 0  , # empty site
            'H'  : 1  ,
            'D'  : 1  ,
            'He' : 2  ,
            'Li' : 3  ,
            'Be' : 4  ,
            'B'  : 5  ,
            'C'  : 6  ,
            'N'  : 7  ,
            'O'  : 8  ,
            'F'  : 9  ,
            'Ne' : 10 ,
            'Na' : 11 ,
            'Mg' : 12 ,
            'Al' : 13 ,
            'Si' : 14 ,
            'P'  : 15 ,
            'S'  : 16 ,
            'Cl' : 17 ,
            'Ar' : 18 ,
            'K'  : 19 ,
            'Ca' : 20 ,
            'Sc' : 21 ,
            'Ti' : 22 ,
            'V'  : 23 ,
            'Cr' : 24 ,
            'Mn' : 25 ,
            'Fe' : 26 ,
            'Co' : 27 ,
            'Ni' : 28 ,
            'Cu' : 29 ,
            'Zn' : 30 ,
            'Ga' : 31 ,
            'Ge' : 32 ,
            'As' : 33 ,
            'Se' : 34 ,
            'Br' : 35 ,
            'Kr' : 36 ,
            'Rb' : 37 ,
            'Sr' : 38 ,
            'Y'  : 39 ,
            'Zr' : 40 ,
            'Nb' : 41 ,
            'Mo' : 42 ,
            'Tc' : 43 ,
            'Ru' : 44 ,
            'Rh' : 45 ,
            'Pd' : 46 ,
            'Ag' : 47 ,
            'Cd' : 48 ,
            'In' : 49 ,
            'Sn' : 50 ,
            'Sb' : 51 ,
            'Te' : 52 ,
            'I'  : 53 ,
            'Xe' : 54 ,
            'Cs' : 55 ,
            'Ba' : 56 ,
            'La' : 57 ,
            'Ce' : 58 ,
            'Pr' : 59 ,
            'Nd' : 60 ,
            'Pm' : 61 ,
            'Sm' : 62 ,
            'Eu' : 63 ,
            'Gd' : 64 ,
            'Tb' : 65 ,
            'Dy' : 66 ,
            'Ho' : 67 ,
            'Er' : 68 ,
            'Tm' : 69 ,
            'Yb' : 70 ,
            'Lu' : 71 ,
            'Hf' : 72 ,
            'Ta' : 73 ,
            'W'  : 74 ,
            'Re' : 75 ,
            'Os' : 76 ,
            'Ir' : 77 ,
            'Pt' : 78 ,
            'Au' : 79 ,
            'Hg' : 80 ,
            'Tl' : 81 ,
            'Pb' : 82 ,
            'Bi' : 83 ,
            'Po' : 84 ,
            'At' : 85 ,
            'Rn' : 86 ,
            'Fr' : 87 ,
            'Ra' : 88 ,
            'Ac' : 89 ,
            'Th' : 90 ,
            'Pa' : 91 ,
            'U'  : 92 ,
            'Np' : 93 ,
            'Pu' : 94 ,
            'Am' : 95 ,
            'Cm' : 96 ,
            'Bk' : 97 ,
            'Cf' : 98 ,
            'Es' : 99 ,
            'Fm' : 100,
            'Me' : 101,
            'No' : 102,
            'Lr' : 103,
            'Rf' : 104,
            'Db' : 105,
            'Sg' : 106,
            'Bh' : 107,
            'Hs' : 108,
            'Mt' : 109,
            'Uun': 110,
            'Uuu': 111,
            'Uub': 112}
        
        self.valenceelectrons = {
            'Em' : 0  , # empty site 
            'Vc' : 0  , # empty site
            'Va' : 0  , # empty site
            'H'  : 1  ,
            'D'  : 1  ,
            'He' : 0  ,
            'Li' : 1  ,
            'Be' : 2  ,
            'B'  : 3  ,
            'C'  : 4  ,
            'N'  : 5  ,
            'O'  : 6  ,
            'F'  : 7  ,
            'Ne' : 0 ,
            'Na' : 1 ,
            'Mg' : 2 ,
            'Al' : 3 ,
            'Si' : 4 ,
            'P'  : 5 ,
            'S'  : 6 ,
            'Cl' : 7 ,
            'Ar' : 0 ,
            'K'  : 1 ,
            'Ca' : 2 ,
            'Sc' : 3 ,
            'Ti' : 4 ,
            'V'  : 5 ,
            'Cr' : 6 ,
            'Mn' : 7 ,
            'Fe' : 8 ,
            'Co' : 9 ,
            'Ni' : 10 ,
            'Cu' : 1 ,
            'Zn' : 2 ,
            'Ga' : 3 ,
            'Ge' : 4 ,
            'As' : 5 ,
            'Se' : 6 ,
            'Br' : 7 ,
            'Kr' : 0 ,
            'Rb' : 1 ,
            'Sr' : 2 ,
            'Y'  : 3 ,
            'Zr' : 4 ,
            'Nb' : 5 ,
            'Mo' : 6 ,
            'Tc' : 7 ,
            'Ru' : 8 ,
            'Rh' : 9 ,
            'Pd' : 10 ,
            'Ag' : 1 ,
            'Cd' : 2 ,
            'In' : 3 ,
            'Sn' : 4 ,
            'Sb' : 5 ,
            'Te' : 6 ,
            'I'  : 7 ,
            'Xe' : 0 ,
            'Cs' : 1 ,
            'Ba' : 2 ,
            'La' : 3 ,
            'Ce' : 2 ,
            'Pr' : 2 ,
            'Nd' : 2 ,
            'Pm' : 2 ,
            'Sm' : 2 ,
            'Eu' : 2 ,
            'Gd' : 2 ,
            'Tb' : 2 ,
            'Dy' : 2 ,
            'Ho' : 2 ,
            'Er' : 2 ,
            'Tm' : 2 ,
            'Yb' : 2 ,
            'Lu' : 3 ,
            'Hf' : 4 ,
            'Ta' : 5 ,
            'W'  : 6 ,
            'Re' : 7 ,
            'Os' : 8 ,
            'Ir' : 9 ,
            'Pt' : 10 ,
            'Au' : 1 ,
            'Hg' : 2 ,
            'Tl' : 3 ,
            'Pb' : 4 ,
            'Bi' : 5 ,
            'Po' : 6 ,
            'At' : 7 ,
            'Rn' : 0 ,
            'Fr' : 1 ,
            'Ra' : 2 ,
            'Ac' : 3 ,
            'Th' : 4 ,
            'Pa' : 5 ,
            'U'  : 6 ,
            'Np' : 7 ,
            'Pu' : 8 ,
            'Am' : 2 ,
            'Cm' : 2 ,
            'Bk' : 2 ,
            'Cf' : 2 ,
            'Es' : 2 }
        
        # Periods
        self.elementperiod = {
            'H'  : 1 ,
            'D'  : 1 ,
            'He' : 2 ,
            'Li' : 2 ,
            'Be' : 2 ,
            'B'  : 2 ,
            'C'  : 2 ,
            'N'  : 2 ,
            'O'  : 2 ,
            'F'  : 2 ,
            'Ne' : 2 ,
            'Na' : 3 ,
            'Mg' : 3 ,
            'Al' : 3 ,
            'Si' : 3 ,
            'P'  : 3 ,
            'S'  : 3 ,
            'Cl' : 3 ,
            'Ar' : 3 ,
            'K'  : 4 ,
            'Ca' : 4 ,
            'Sc' : 4 ,
            'Ti' : 4 ,
            'V'  : 4 ,
            'Cr' : 4 ,
            'Mn' : 4 ,
            'Fe' : 4 ,
            'Co' : 4 ,
            'Ni' : 4 ,
            'Cu' : 4 ,
            'Zn' : 4 ,
            'Ga' : 4 ,
            'Ge' : 4 ,
            'As' : 4 ,
            'Se' : 4 ,
            'Br' : 4 ,
            'Kr' : 4 ,
            'Rb' : 5 ,
            'Sr' : 5 ,
            'Y'  : 5 ,
            'Zr' : 5 ,
            'Nb' : 5 ,
            'Mo' : 5 ,
            'Tc' : 5 ,
            'Ru' : 5 ,
            'Rh' : 5 ,
            'Pd' : 5 ,
            'Ag' : 5 ,
            'Cd' : 5 ,
            'In' : 5 ,
            'Sn' : 5 ,
            'Sb' : 5 ,
            'Te' : 5 ,
            'I'  : 5 ,
            'Xe' : 5 ,
            'Cs' : 6 ,
            'Ba' : 6 ,
            'La' : 6 ,
            'Ce' : 6 ,
            'Pr' : 6 ,
            'Nd' : 6 ,
            'Pm' : 6 ,
            'Sm' : 6 ,
            'Eu' : 6 ,
            'Gd' : 6 ,
            'Tb' : 6 ,
            'Dy' : 6 ,
            'Ho' : 6 ,
            'Er' : 6 ,
            'Tm' : 6 ,
            'Yb' : 6 ,
            'Lu' : 6 ,
            'Hf' : 6 ,
            'Ta' : 6 ,
            'W'  : 6 ,
            'Re' : 6 ,
            'Os' : 6 ,
            'Ir' : 6 ,
            'Pt' : 6 ,
            'Au' : 6 ,
            'Hg' : 6 ,
            'Tl' : 6 ,
            'Pb' : 6 ,
            'Bi' : 6 ,
            'Po' : 6 ,
            'At' : 6 ,
            'Rn' : 6 ,
            'Fr' : 7 ,
            'Ra' : 7 ,
            'Ac' : 7 ,
            'Th' : 7 ,
            'Pa' : 7 ,
            'U'  : 7 ,
            'Np' : 7 ,
            'Pu' : 7 ,
            'Am' : 7 ,
            'Cm' : 7 ,
            'Bk' : 7 ,
            'Cf' : 7 ,
            'Es' : 7 ,
            'Fm' : 7 ,
            'Me' : 7 ,
            'No' : 7 ,
            'Lr' : 7 ,
            'Rf' : 7 ,
            'Db' : 7 ,
            'Sg' : 7 ,
            'Bh' : 7 ,
            'Hs' : 7 ,
            'Mt' : 7 ,
            'Uun': 7 ,
            'Uuu': 7 ,
            'Uub': 7 }
        
        # Element classification in s, p, d and f blocks
        self.elementblock = {
            'Em' : 's'  , # empty site
            'Vc' : 's'  , # empty site
            'Va' : 's'  , # empty site 
            'H'  : 's'  ,
            'D'  : 's'  ,
            'He' : 's'  ,
            'Li' : 's'  ,
            'Be' : 's'  ,
            'B'  : 'p'  ,
            'C'  : 'p'  ,
            'N'  : 'p'  ,
            'O'  : 'p'  ,
            'F'  : 'p'  ,
            'Ne' : 'p' ,
            'Na' : 's' ,
            'Mg' : 's' ,
            'Al' : 'p' ,
            'Si' : 'p' ,
            'P'  : 'p' ,
            'S'  : 'p' ,
            'Cl' : 'p' ,
            'Ar' : 'p' ,
            'K'  : 's' ,
            'Ca' : 's' ,
            'Sc' : 'd' ,
            'Ti' : 'd' ,
            'V'  : 'd' ,
            'Cr' : 'd' ,
            'Mn' : 'd' ,
            'Fe' : 'd' ,
            'Co' : 'd' ,
            'Ni' : 'd' ,
            'Cu' : 'd' ,
            'Zn' : 'd' ,
            'Ga' : 'p' ,
            'Ge' : 'p' ,
            'As' : 'p' ,
            'Se' : 'p' ,
            'Br' : 'p' ,
            'Kr' : 'p' ,
            'Rb' : 's' ,
            'Sr' : 's' ,
            'Y'  : 'd' ,
            'Zr' : 'd' ,
            'Nb' : 'd' ,
            'Mo' : 'd' ,
            'Tc' : 'd' ,
            'Ru' : 'd' ,
            'Rh' : 'd' ,
            'Pd' : 'd' ,
            'Ag' : 'd' ,
            'Cd' : 'd' ,
            'In' : 'p' ,
            'Sn' : 'p' ,
            'Sb' : 'p' ,
            'Te' : 'p' ,
            'I'  : 'p' ,
            'Xe' : 'p' ,
            'Cs' : 's' ,
            'Ba' : 's' ,
            'La' : 'f' ,
            'Ce' : 'f' ,
            'Pr' : 'f' ,
            'Nd' : 'f' ,
            'Pm' : 'f' ,
            'Sm' : 'f' ,
            'Eu' : 'f' ,
            'Gd' : 'f' ,
            'Tb' : 'f' ,
            'Dy' : 'f' ,
            'Ho' : 'f' ,
            'Er' : 'f' ,
            'Tm' : 'f' ,
            'Yb' : 'f' ,
            'Lu' : 'f' ,
            'Hf' : 'd' ,
            'Ta' : 'd' ,
            'W'  : 'd' ,
            'Re' : 'd' ,
            'Os' : 'd' ,
            'Ir' : 'd' ,
            'Pt' : 'd' ,
            'Au' : 'd' ,
            'Hg' : 'd' ,
            'Tl' : 'p' ,
            'Pb' : 'p' ,
            'Bi' : 'p' ,
            'Po' : 'p' ,
            'At' : 'p' ,
            'Rn' : 'p' ,
            'Fr' : 's' ,
            'Ra' : 's' ,
            'Ac' : 'f' ,
            'Th' : 'f' ,
            'Pa' : 'f' ,
            'U'  : 'f' ,
            'Np' : 'f' ,
            'Pu' : 'f' ,
            'Am' : 'f' ,
            'Cm' : 'f' ,
            'Bk' : 'f' ,
            'Cf' : 'f' ,
            'Es' : 'f' ,
            'Fm' : 'f',
            'Me' : 'f',
            'No' : 'f',
            'Lr' : 'd',
            'Rf' : 'd',
            'Db' : 'd',
            'Sg' : 'd',
            'Bh' : 'd',
            'Hs' : 'd',
            'Mt' : 'd',
            'Uun': 'd',
            'Uuu': 'd',
            'Uub': 'd' }

        # Angular momentum quantum numbers
        self.angularmomentum = { 's' : 0, 'p' : 1, 'd' : 2, 'f' : 3 }

        self.elementweight = {
            'H' : 1.0075,
            'D' : 2.01410178,
            'He' : 4.002,
            'Li' : 6.9675,
            'Be' : 9.012,
            'B' : 10.8135,
            'C' : 12.0106,
            'N' : 14.0065,
            'O' : 15.999,
            'F' : 18.998,
            'Ne' : 20.1797,
            'Na' : 22.989,
            'Mg' : 24.3050,
            'Al' : 26.981,
            'Si' : 28.085,
            'P' : 30.973,
            'S' : 32.0675,
            'Cl' : 35.4515,
            'Ar' : 39.948,
            'K' : 39.0983,
            'Ca' : 40.078,
            'Sc' : 44.955,
            'Ti' : 47.867,
            'V' : 50.9415,
            'Cr' : 51.9961,
            'Mn' : 54.938,
            'Fe' : 55.845,
            'Co' : 58.933,
            'Ni' : 58.6934,
            'Cu' : 63.546,
            'Zn' : 65.38,
            'Ga' : 69.723,
            'Ge' : 72.63,
            'As' : 74.921,
            'Se' : 78.96,
            'Br' : 79.904,
            'Kr' : 83.798,
            'Rb' : 85.4678,
            'Sr' : 87.62,
            'Y' : 88.905,
            'Zr' : 91.224,
            'Nb' : 92.906,
            'Mo' : 95.96,
            'Tc' : 98,
            'Ru' : 101.07,
            'Rh' : 102.905,
            'Pd' : 106.42,
            'Ag' : 107.8682,
            'Cd' : 112.411,
            'In' : 114.818,
            'Sn' : 118.710,
            'Sb' : 121.760,
            'Te' : 127.60,
            'I' : 126.904,
            'Xe' : 131.293,
            'Cs' : 132.905,
            'Ba' : 137.327,
            'La' : 138.905,
            'Ce' : 140.116,
            'Pr' : 140.907,
            'Nd' : 144.242,
            'Pm' : 145,
            'Sm' : 150.36,
            'Eu' : 151.964,
            'Gd' : 157.25,
            'Tb' : 158.925,
            'Dy' : 162.500,
            'Ho' : 164.930,
            'Er' : 167.259,
            'Tm' : 168.934,
            'Yb' : 173.054,
            'Lu' : 174.9668,
            'Hf' : 178.49,
            'Ta' : 180.947,
            'W' : 183.84,
            'Re' : 186.207,
            'Os' : 190.23,
            'Ir' : 192.217,
            'Pt' : 195.084,
            'Au' : 196.966,
            'Hg' : 200.59,
            'Tl' : 204.3835,
            'Pb' : 207.2,
            'Bi' : 208.980,
            'Po' : 209,
            'At' : 210,
            'Rn' : 222,
            'Fr' : 223,
            'Ra' : 226,
            'Ac' : 227,
            'Th' : 232.038,
            'Pa' : 231.035,
            'U' : 238.028,
            'Np' : 237,
            'Pu' : 244,
            'Am' : 243,
            'Cm' : 247,
            'Bk' : 247,
            'Cf' : 251,
            'Es' : 252,
            'Fm' : 257,
            'Md' : 258,
            'No' : 259,
            'Lr' : 262,
            'Rf' : 267,
            'Db' : 268,
            'Sg' : 271,
            'Bh' : 272,
            'Hs' : 270,
            'Mt' : 276,
            'Ds' : 281,
            'Rg' : 280,
            'Cn' : 285 }
 
        self.vasp_pot = {
            'H'  : 'H'  ,
            'D'  : 'H'  ,
            'He' : 'He'  ,
            'Li' : 'Li_sv'  ,
            'Be' : 'Be'  ,
            'B'  : 'B'  ,
            'C'  : 'C'  ,
            'N'  : 'N'  ,
            'O'  : 'O'  ,
            'F'  : 'F'  ,
            'Ne' : 'Ne' ,
            'Na' : 'Na_pv' ,
            'Mg' : 'Mg' ,
            'Al' : 'Al' ,
            'Si' : 'Si' ,
            'P'  : 'P' ,
            'S'  : 'S' ,
            'Cl' : 'Cl' ,
            'Ar' : 'Ar' ,
            'K'  : 'K_sv' ,
            'Ca' : 'Ca_sv' ,
            'Sc' : 'Sc_sv' ,
            'Ti' : 'Ti_sv' ,
            'V'  : 'V_sv' ,
            'Cr' : 'Cr_pv' ,
            'Mn' : 'Mn_pv' ,
            'Fe' : 'Fe' ,
            'Co' : 'Co' ,
            'Ni' : 'Ni' ,
            'Cu' : 'Cu' ,
            'Zn' : 'Zn' ,
            'Ga' : 'Ga_d' ,
            'Ge' : 'Ge_d' ,
            'As' : 'As' ,
            'Se' : 'Se' ,
            'Br' : 'Br' ,
            'Kr' : 'Kr' ,
            'Rb' : 'Rb_sv' ,
            'Sr' : 'Sr_sv' ,
            'Y'  : 'Y_sv' ,
            'Zr' : 'Zr_sv' ,
            'Nb' : 'Nb_sv' ,
            'Mo' : 'Mo_sv' ,
            'Tc' : 'Tc_pv' ,
            'Ru' : 'Ru_pv' ,
            'Rh' : 'Rh_pv' ,
            'Pd' : 'Pd' ,
            'Ag' : 'Ag' ,
            'Cd' : 'Cd' ,
            'In' : 'In_d' ,
            'Sn' : 'Sn_d' ,
            'Sb' : 'Sb' ,
            'Te' : 'Te' ,
            'I'  : 'I' ,
            'Xe' : 'Xe' ,
            'Cs' : 'Cs_sv' ,
            'Ba' : 'Ba_sv' ,
            'La' : 'La' ,
            'Ce' : 'Ce' ,
            'Pr' : 'Pr_3' ,
            'Nd' : 'Nd_3' ,
            'Pm' : 'Pm_3' ,
            'Sm' : 'Sm_3' ,
            'Eu' : 'Eu_2' ,
            'Gd' : 'Gd_3' ,
            'Tb' : 'Tb_3' ,
            'Dy' : 'Dy_3' ,
            'Ho' : 'Ho_3' ,
            'Er' : 'Er_3' ,
            'Tm' : 'Tm_3' ,
            'Yb' : 'Yb_2' ,
            'Lu' : 'Lu_3' ,
            'Hf' : 'Hf_pv' ,
            'Ta' : 'Ta_pv' ,
            'W'  : 'W_pv' ,
            'Re' : 'Re' ,
            'Os' : 'Os' ,
            'Ir' : 'Ir' ,
            'Pt' : 'Pt' ,
            'Au' : 'Au' ,
            'Hg' : 'Hg' ,
            'Tl' : 'Tl_d' ,
            'Pb' : 'Pb_d' ,
            'Bi' : 'Bi_d' ,
            'Po' : 'Po_d' ,
            'At' : 'At_d' ,
            'Rn' : 'Rn' ,
            'Fr' : 'Fr_sv' ,
            'Ra' : 'Ra_sv' ,
            'Ac' : 'Ac' ,
            'Th' : 'Th' ,
            'Pa' : 'Pa' ,
            'U'  : 'U' ,
            'Np' : 'Np' ,
            'Pu' : 'Pu' ,
            'Am' : 'Am' ,
            'Cm' : 'Cm'}


        self.vasp_cutoff = {
            'H'  : 250 ,
            'D'  : 250 ,
            'He' : 479 ,
            'Li' : 499 ,
            'Be' : 248 ,
            'B'  : 319 ,
            'C'  : 400 ,
            'N'  : 400 ,
            'O'  : 400 ,
            'F'  : 400 ,
            'Ne' : 344 ,
            'Na' : 260 ,
            'Mg' : 200 ,
            'Al' : 240 ,
            'Si' : 245 ,
            'P'  : 255 ,
            'S'  : 259 ,
            'Cl' : 262 ,
            'Ar' : 266 ,
            'K'  : 259 ,
            'Ca' : 267 ,
            'Sc' : 223 ,
            'Ti' : 275 ,
            'V'  : 264 ,
            'Cr' : 266 ,
            'Mn' : 270 ,
            'Fe' : 268 ,
            'Co' : 268 ,
            'Ni' : 270 ,
            'Cu' : 295 ,
            'Zn' : 277 ,
            'Ga' : 283 ,
            'Ge' : 310 ,
            'As' : 209 ,
            'Se' : 212 ,
            'Br' : 216 ,
            'Kr' : 185 ,
            'Rb' : 220 ,
            'Sr' : 229 ,
            'Y'  : 203 ,
            'Zr' : 230 ,
            'Nb' : 293 ,
            'Mo' : 243 ,
            'Tc' : 264 ,
            'Ru' : 240 ,
            'Rh' : 247 ,
            'Pd' : 251 ,
            'Ag' : 250 ,
            'Cd' : 274 ,
            'In' : 239 ,
            'Sn' : 241 ,
            'Sb' : 172 ,
            'Te' : 175 ,
            'I'  : 176 ,
            'Xe' : 153 ,
            'Cs' : 220 ,
            'Ba' : 187 ,
            'La' : 219 ,
            'Ce' : 273 ,
            'Pr' : 182 ,
            'Nd' : 183 ,
            'Pm' : 177 ,
            'Sm' : 177 ,
            'Eu' : 99 ,
            'Gd' : 154 ,
            'Tb' : 156 ,
            'Dy' : 156 ,
            'Ho' : 154 ,
            'Er' : 155 ,
            'Tm' : 149 ,
            'Yb' : 113 ,
            'Lu' : 155 ,
            'Hf' : 220 ,
            'Ta' : 224 ,
            'W'  : 223 ,
            'Re' : 226 ,
            'Os' : 228 ,
            'Ir' : 211 ,
            'Pt' : 230 ,
            'Au' : 230 ,
            'Hg' : 233 ,
            'Tl' : 237 ,
            'Pb' : 238 ,
            'Bi' : 243 ,
            'Po' : 265 ,
            'At' : 266 ,
            'Rn' : 152 ,
            'Fr' : 215 ,
            'Ra' : 237 ,
            'Ac' : 172 ,
            'Th' : 247 ,
            'Pa' : 252 ,
            'U'  : 253 ,
            'Np' : 254 ,
            'Pu' : 254 ,
            'Am' : 256 ,
            'Cm' : 258}

        self.castep_recpot = {
            'H'  : 'H_00PBE_OP.recpot'  ,
            'D'  : 'H_00PBE_OP.recpot'  ,
            'He' : 'He_00.recpot'  ,
            'Li' : 'Li_00.recpot'  ,
            'Be' : 'Be_00.recpot'  ,
            'B'  : 'B_00PBE_OP.recpot'  ,
            'C'  : 'C_00PBE_OP.recpot'  ,
            'N'  : 'N_00PBE_OP.recpot'  ,
            'O'  : 'O_00PBE_OP.recpot'  ,
            'F'  : 'F_00.recpot'  ,
            'Ne' : 'Ne_00.recpot' ,
            'Na' : 'Na_00.recpot' ,
            'Mg' : 'Mg_00PBE_OP.recpot' ,
            'Al' : 'Al_00.recpot' ,
            'Si' : 'Si_00PBE_OP.recpot' ,
            'P'  : 'P_00PBE_OP.recpot' ,
            'S'  : 'S_00PBE_OP.recpot' ,
            'Cl' : 'Cl_00PBE_OP.recpot' ,
            'Ar' : 'Ar_00.recpot' ,
            'K'  : 'K_00.recpot' ,
            'Ca' : 'Ca_00PBE_OP.recpot' ,
            'Sc' : 'Sc_00.recpot' ,
            'Ti' : 'Ti_00PBE_OP.recpot' ,
            'V'  : 'V_00.recpot' ,
            'Cr' : 'Cr_00.recpot' ,
            'Mn' : 'Mn_00.recpot' ,
            'Fe' : 'Fe_00PBE_OP.recpot' ,
            'Co' : 'Co_00.recpot' ,
            'Ni' : 'Ni_00PBE_OP.recpot' ,
            'Cu' : 'Cu_00.recpot' ,
            'Zn' : 'Zn_00.recpot' ,
            'Ga' : 'Ga_00.recpot' ,
            'Ge' : 'Ge_00PBE_OP.recpot' ,
            'As' : 'As_00.recpot' ,
            'Se' : 'Se_00.recpot' ,
            'Br' : 'Br_00.recpot' ,
            'Kr' : 'Kr_00.recpot' ,
            'Rb' : 'Rb_00.recpot' ,
            'Sr' : 'Sr_00.recpot' ,
            'Y'  : 'Y_00.recpot' ,
            'Zr' : 'Zr_00PBE_OP.recpot' ,
            'Nb' : 'Nb_00.recpot' ,
            'Mo' : 'Mo_00.recpot' ,
            'Tc' : 'Tc_00.recpot' ,
            'Ru' : 'Ru_00.recpot' ,
            'Rh' : 'Rh_00.recpot' ,
            'Pd' : 'Pd_00PBE_OP.recpot' ,
            'Ag' : 'Ag_00PBE_OP.recpot' ,
            'Cd' : 'Cd_00.recpot' ,
            'In' : 'In_00.recpot' ,
            'Sn' : 'Sn_00.recpot' ,
            'Sb' : 'Sb_00.recpot' ,
            'Te' : 'Te_00.recpot' ,
            'I'  : 'I_00.recpot' ,
            'Xe' : 'Xe_00.recpot' ,
            'Cs' : 'Cs_00.recpot' ,
            'Ba' : 'Ba_00PBE_OP.recpot' ,
            'La' : 'La_00.recpot' ,
            'Ce' : 'Ce_00.recpot' ,
            'Sm' : 'Sm_00.recpot' ,
            'Gd' : 'Gd_00.recpot' ,
            'Lu' : 'Lu_00.recpot' ,
            'Hf' : 'Hf_00.recpot' ,
            'Ta' : 'Ta_00.recpot' ,
            'W'  : 'W_00.recpot' ,
            'Re' : 'Re_00.recpot' ,
            'Os' : 'Os_00.recpot' ,
            'Ir' : 'Ir_00.recpot' ,
            'Pt' : 'Pt_00PBE_OP.recpot' ,
            'Au' : 'Au_00.recpot' ,
            'Hg' : 'Hg_00.recpot' ,
            'Tl' : 'Tl_00.recpot' ,
            'Pb' : 'Pb_00PBE_OP.recpot' ,
            'Bi' : 'Bi_00.recpot' ,
            'Po' : 'Po_00.recpot' ,
            'At' : 'At_00.recpot' ,
            'Rn' : 'Rn_00.recpot' ,
            'Fr' : 'Fr_00.recpot' ,
            'Ra' : 'Ra_00.recpot' ,
            'Ac' : 'Ac_00.recpot' ,
            'Th' : 'Th_00PBE.recpot'}

        self.castep_usp = {
            'H'  : 'H_00PBE.usp'  ,
            'D'  : 'H_00PBE.usp'  ,
            'He' : 'He_00.usp'  ,
            'Li' : 'Li_00PBE.usp'  ,
            'Be' : 'Be_00PBE.usp'  ,
            'B'  : 'B_00PBE.usp'  ,
            'C'  : 'C_00PBE.usp'  ,
            'N'  : 'N_00PBE.usp'  ,
            'O'  : 'O_00PBE.usp'  ,
            'F'  : 'F_00PBE.usp'  ,
            'Ne' : 'Ne_00.usp' ,
            'Na' : 'Na_00PBE.usp' ,
            'Mg' : 'Mg_00PW91.usp' ,
            'Al' : 'Al_00PBE.usp' ,
            'Si' : 'Si_00PBE.usp' ,
            'P'  : 'P_00PBE.usp' ,
            'S'  : 'S_00PBE.usp' ,
            'Cl' : 'Cl_00PBE.usp' ,
            'Ar' : 'Ar_00.usp' ,
            'K'  : 'K_00PBE.usp' ,
            'Ca' : 'Ca_00PBE.usp' ,
            'Sc' : 'Sc_00.usp' ,
            'Ti' : 'Ti_00PBE.usp' ,
            'V'  : 'V_00PBE.usp' ,
            'Cr' : 'Cr_00PBE.usp' ,
            'Mn' : 'Mn_00PBE.usp' ,
            'Fe' : 'Fe_00PBE.usp' ,
            'Co' : 'Co_00PBE.usp' ,
            'Ni' : 'Ni_00PBE.usp' ,
            'Cu' : 'Cu_00PBE.usp' ,
            'Zn' : 'Zn_00PBE.usp' ,
            'Ga' : 'Ga_00PBE.usp' ,
            'Ge' : 'Ge_00PBE.usp' ,
            'As' : 'As_00PBE.usp' ,
            'Se' : 'Se_00.usp' ,
            'Br' : 'Br_00PBE.usp' ,
            'Kr' : 'Kr_00.usp' ,
            'Rb' : 'Rb_00PBE.usp' ,
            'Sr' : 'Sr_00PBE.usp' ,
            'Y'  : 'Y_00PW91.usp' ,
            'Zr' : 'Zr_00PBE.usp' ,
            'Nb' : 'Nb_00PBE.usp' ,
            'Mo' : 'Mo_00PBE.usp' ,
            'Tc' : 'Tc_00PBE.usp' ,
            'Ru' : 'Ru_00PBE.usp' ,
            'Rh' : 'Rh_00PBE.usp' ,
            'Pd' : 'Pd_00PBE.usp' ,
            'Ag' : 'Ag_00PBE.usp' ,
            'Cd' : 'Cd_00PBE.usp' ,
            'In' : 'In_00PBE.usp' ,
            'Sn' : 'Sn_00PBE.usp' ,
            'Sb' : 'Sb_00PBE.usp' ,
            'Te' : 'Te_00PBE.usp' ,
            'I'  : 'I_00PBE.usp' ,
            'Xe' : 'Xe_00.usp' ,
            'Cs' : 'Cs_00.usp' ,
            'Ba' : 'Ba_00PBE.usp' ,
            'La' : 'La_00PBE.usp' ,
            'Ce' : 'Ce_00PBE.usp' ,
            'Pr' : 'Pr_00.usp' ,
            'Nd' : 'Nd_00.usp' ,
            'Pm' : 'Pm_00.usp' ,
            'Sm' : 'Sm_00.usp' ,
            'Eu' : 'Eu_00.usp' ,
            'Gd' : 'Gd_00.usp' ,
            'Tb' : 'Tb_00.usp' ,
            'Dy' : 'Dy_00.usp' ,
            'Ho' : 'Ho_00PBE.usp' ,
            'Er' : 'Er_00.usp' ,
            'Tm' : 'Tm_00.usp' ,
            'Yb' : 'Yb_00PBE.usp' ,
            'Lu' : 'Lu_00.usp' ,
            'Hf' : 'Hf_00PBE.usp' ,
            'Ta' : 'Ta_00PBE.usp' ,
            'W'  : 'W_00PBE.usp' ,
            'Re' : 'Re_00PBE.usp' ,
            'Os' : 'Os_00PBE.usp' ,
            'Ir' : 'Ir_00PBE.usp' ,
            'Pt' : 'Pt_00PBE.usp' ,
            'Au' : 'Au_00PBE.usp' ,
            'Hg' : 'Hg_00PBE.usp' ,
            'Tl' : 'Tl_00PBE.usp' ,
            'Pb' : 'Pb_00PBE.usp' ,
            'Bi' : 'Bi_00PBE.usp' ,
            'Po' : 'Po_00.usp' ,
            'At' : 'At_00.usp' ,
            'Rn' : 'Rn_00.usp' ,
            'Fr' : 'Fr_00.usp' ,
            'Ra' : 'Ra_00.usp' ,
            'Th' : 'Th_00.usp' ,
            'Pa' : 'Pa_00.usp' ,
            'U'  : 'U_00PBE.usp' ,
            'Np' : 'Np_00.usp' ,
            'Pu' : 'Pu_00PBE.usp' ,
            'Am' : 'Am_00.usp' ,
            'Cm' : 'Cm_00PBE.usp'}


        self.castep_recpot_cutoff = {
            'H'  : 650 ,
            'D'  : 650 ,
            'He' : 1400 ,
            'Li' : 450 ,
            'Be' : 400 ,
            'B'  : 489 ,
            'C'  : 680 ,
            'N'  : 700 ,
            'O'  : 750 ,
            'F'  : 850 ,
            'Ne' : 500 ,
            'Na' : 700 ,
            'Mg' : 900 ,
            'Al' : 200 ,
            'Si' : 350 ,
            'P'  : 450 ,
            'S'  : 650 ,
            'Cl' : 750 ,
            'Ar' : 350 ,
            'K'  : 300 ,
            'Ca' : 800 ,
            'Sc' : 400 ,
            'Ti' : 700 ,
            'V'  : 400 ,
            'Cr' : 700 ,
            'Mn' : 400 ,
            'Fe' : 900 ,
            'Co' : 550 ,
            'Ni' : 780 ,
            'Cu' : 600 ,
            'Zn' : 600 ,
            'Ga' : 800 ,
            'Ge' : 400 ,
            'As' : 300 ,
            'Se' : 400 ,
            'Br' : 250 ,
            'Kr' : 300 ,
            'Rb' : 300 ,
            'Sr' : 600 ,
            'Y'  : 300 ,
            'Zr' : 650 ,
            'Nb' : 350 ,
            'Mo' : 400 ,
            'Tc' : 400 ,
            'Ru' : 400 ,
            'Rh' : 400 ,
            'Pd' : 850 ,
            'Ag' : 765 ,
            'Cd' : 600 ,
            'In' : 200 ,
            'Sn' : 200 ,
            'Sb' : 300 ,
            'Te' : 250 ,
            'I'  : 400 ,
            'Xe' : 350 ,
            'Cs' : 400 ,
            'Ba' : 370 ,
            'La' : 300 ,
            'Ce' : 700 ,
            'Sm' : 700 ,
            'Gd' : 820 ,
            'Lu' : 900 ,
            'Hf' : 300 ,
            'Ta' : 350 ,
            'W'  : 450 ,
            'Re' : 400 ,
            'Os' : 400 ,
            'Ir' : 500 ,
            'Pt' : 750 ,
            'Au' : 500 ,
            'Hg' : 450 ,
            'Tl' : 450 ,
            'Pb' : 820 ,
            'Bi' : 500 ,
            'Po' : 500 ,
            'At' : 500 ,
            'Rn' : 450 ,
            'Fr' : 400 ,
            'Ra' : 400 ,
            'Ac' : 300 ,
            'Th' : 983}

        self.castep_usp_cutoff = {
            'H'  : 230 ,
            'D'  : 230 ,
            'He' : 340  ,
            'Li' : 300 ,
            'Be' : 180 ,
            'B'  : 240 ,
            'C'  : 280 ,
            'N'  : 250 ,
            'O'  : 340 ,
            'F'  : 330 ,
            'Ne' : 270 ,
            'Na' : 370 ,
            'Mg' : 340 ,
            'Al' : 140 ,
            'Si' : 150 ,
            'P'  : 160 ,
            'S'  : 220 ,
            'Cl' : 230 ,
            'Ar' : 250 ,
            'K'  : 200 ,
            'Ca' : 280 ,
            'Sc' : 290 ,
            'Ti' : 310 ,
            'V'  : 280 ,
            'Cr' : 310 ,
            'Mn' : 320 ,
            'Fe' : 300 ,
            'Co' : 320 ,
            'Ni' : 300 ,
            'Cu' : 400 ,
            'Zn' : 310 ,
            'Ga' : 295 ,
            'Ge' : 180 ,
            'As' : 300 ,
            'Se' : 240 ,
            'Br' : 160 ,
            'Kr' : 310 ,
            'Rb' : 180 ,
            'Sr' : 230 ,
            'Y'  : 260 ,
            'Zr' : 245 ,
            'Nb' : 320 ,
            'Mo' : 290 ,
            'Tc' : 290 ,
            'Ru' : 300 ,
            'Rh' : 280 ,
            'Pd' : 300 ,
            'Ag' : 300 ,
            'Cd' : 260 ,
            'In' : 310 ,
            'Sn' : 250 ,
            'Sb' : 205 ,
            'Te' : 190 ,
            'I'  : 210 ,
            'Xe' : 230 ,
            'Cs' : 240 ,
            'Ba' : 160 ,
            'La' : 240 ,
            'Ce' : 370 ,
            'Pr' : 420 ,
            'Nd' : 400 ,
            'Pm' : 430 ,
            'Sm' : 380 ,
            'Eu' : 430 ,
            'Gd' : 360 ,
            'Tb' : 300 ,
            'Dy' : 360 ,
            'Ho' : 300 ,
            'Er' : 320 ,
            'Tm' : 410 ,
            'Yb' : 450 ,
            'Lu' : 350 ,
            'Hf' : 260 ,
            'Ta' : 300 ,
            'W'  : 272 ,
            'Re' : 280 ,
            'Os' : 300 ,
            'Ir' : 310 ,
            'Pt' : 250 ,
            'Au' : 320 ,
            'Hg' : 310 ,
            'Tl' : 250 ,
            'Pb' : 260 ,
            'Bi' : 210 ,
            'Po' : 270 ,
            'At' : 240 ,
            'Rn' : 320 ,
            'Fr' : 240 ,
            'Ra' : 240 ,
            'Th' : 410 ,
            'Pa' : 360 ,
            'U'  : 350 ,
            'Np' : 340 ,
            'Pu' : 380 ,
            'Am' : 320 ,
            'Cm' : 340}

