#!/usr/bin/env perl

#    Copyright (c) Keith Refson 1998-2012
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

use Cwd 'abs_path';
BEGIN {$mypath = $0;
       $mypath = abs_path($mypath);
       if ($mypath =~ /^[A-Za-z]:/) {$mypath =~ s@[^\\]+$@@; } else {$mypath =~ s@[^/]+$@@;}
     }
use lib "$mypath";
use ceteprouts;

if ( $ARGV[0] eq "-b" && $#ARGV > 5 ) {
    shift @ARGV;
    while ($#box < 5 ) {
	push @box, shift @ARGV;
    }
}

if ( $ARGV[0] eq "-n" && $#ARGV > 1 ) {
    shift @ARGV;
    $basename = shift @ARGV if $#ARGV >= 0;
}

$filename = shift @ARGV if $#ARGV >= 0;
unshift @ARGV,$filename;
$basename = $filename if $basename eq "";

ReadNewtepGeom (\&NullFunc, \&WriteFile, \&WriteExpandedPDB, \&NullFunc, $basename.".%.3d.pdb", \@box);
