set(CMAKE_FIND_ROOT_PATH 

/opt/pgi/14.2.0/linux86-64/14.2/libso/
#/opt/pgi/14.2.0/linux86-64/14.2/lib/
#/sw/xk6/boost/1.60.0/sles11.3_gnu4.9.0_shared_python343
/opt/cray/fftw/3.3.4.11/x86_64/
/sw/xk6/boost/1.57.0/cle5.2up04_gnu4.9.0
/ccs/home/z8j/softwares/spglib-1.9.9/build/
/ccs/home/z8j/softwares/libxc-2.2.3/build/
/ccs/home/z8j/softwares/bzip2-1.0.6/build/
/ccs/home/z8j/softwares/pfft/build/

)
